import Head from 'next/head'
import { Header } from '@/components/app/Header'
import { StateChain } from '@/components/app/ui/StateChain'


function index() {
  return (
    <>
    <Head>
      <title>app</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
    <Header />
    <div className='w-full BodyHeight flex justify-center items-center'>
        <StateChain />
    </div>
    </main>
  </>
  )
}

export default index