import { Header } from '@/components/auth/authUi/Header'
import { Container } from '@/ui/Container'
import Head from 'next/head'
import { RegisterForm } from '@/components/auth/authUi/RegisterForm'
function register() {
  return (
    <>
    <Head>
       <title>sonatrach make an account</title>
       <meta name="description" content="Generated by create next app" />
       <meta name="viewport" content="width=device-width, initial-scale=1" />
       <link rel="icon" href="/favicon.ico" />
     </Head>

  <Container>
   <Header />
  <div className='w-full pt-12 flex justify-center items-center'>
  <RegisterForm />
  </div>
  </Container>
  </>
  )
}

export default register