import { StakeholdersForm } from '@/components/startup/StakeholdersForm'
import { SideBarStartUp } from '@/components/startup/SideBarStartUp'
import { FormLayout } from '@/ui/FormLayout'
import Head from 'next/head'
import React from 'react'
import { layout } from '@/ui/styles'



export default function stakeholders() {
  return (
    <>
    <Head>
    <title>app</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main className='w-full h-screen flex ' >
  <SideBarStartUp />
 
  <FormLayout className={`${layout.formInputSection} p-4`}>
  <h2 className='text-white font-bold text-4xl m-4 '>stake Holders </h2>
      <StakeholdersForm />
  </FormLayout>
  </main>
  </>
  )
}

